### PR TITLE
User deck page

### LINKED ISSUE #11: view users owned cards

### LINKED ISSUE #23: Deck View Page
deprecated.

### LINKED ISSUE #47: Handle exceptions properly

### PR DESCRIPTION
**Pull request by idafum**
Fixes #47 
Fixes #11 
Fixes #23

### CODE REVIEW

File: MauiProgram.cs [hunk 1]
```diff
@@ -24,17 +24,17 @@ public static MauiApp CreateMauiApp()
...
 
-        // Register LoginViewModel as a transient service
-        builder.Services.AddTransient<LoginViewModel>();
+        // // Register LoginViewModel as a transient service
+        // builder.Services.AddTransient<LoginViewModel>();
 
-        // Register LoginPage and other pages
-        builder.Services.AddTransient<LoginPage>();
+        // // Register LoginPage and other pages
+        // builder.Services.AddTransient<LoginPage>();
```
Comment (VanJackal) [inline MauiProgram.cs:37]: dead code

File: Services/BackendService.cs [hunk 2]
```diff
@@ -51,12 +54,79 @@ public async Task CreateAccountAsync(UserCredentials credentials)
...
+                }
+            }
+            catch (RestException)
+            {
+                throw; // throw the exception
+            }
+            catch (Exception)
+            {
+                throw;
+            }
```
Comment (VanJackal) [inline Services/BackendService.cs:101]: this is kinda redundant

File: Services/BackendService.cs [hunk 3]
```diff
@@ -51,12 +54,79 @@ public async Task CreateAccountAsync(UserCredentials credentials)
...
+                    }
+                    else
+                    {
+                        throw new Exception("Invalid card filter query");
+                    }
+                }
+                else
+                {
+                    throw new Exception("Invalid user");
+                }
```
Comment (VanJackal) [inline Services/BackendService.cs:92]: instead of nesting the ifs here, maybe just pre check the conditions and throw an exception if user/query is null

File: Services/BackendService.cs [hunk 4]
```diff
@@ -51,12 +54,79 @@ public async Task CreateAccountAsync(UserCredentials credentials)
...
+            }
+            catch (RestException)
+            {
+                throw; // throw the exception
+            }
```
Comment (VanJackal) [inline Services/BackendService.cs:97]: if we arent doing additional processing with the exception there is no reason to catch it

File: Services/BackendService.cs [hunk 5]
```diff
@@ -51,12 +54,79 @@ public async Task CreateAccountAsync(UserCredentials credentials)
...
+            catch (Exception)
+            {
+                throw;
+            }
+        }
```
Comment (VanJackal) [inline Services/BackendService.cs:130]: comments from try/catch in GetCardsAsync apply here aswell

File: ViewModels/DeckViewModel.cs [hunk 6]
```diff
@@ -42,73 +37,114 @@ public Deck SelectedDeck
...
+            catch (RestException ex)
+            {
+                HasDecks = false;
+                Console.WriteLine(ex.Message);
+            }
+            catch (Exception ex)
+            {
+                HasDecks = false;
+                Console.WriteLine($"General error occurred: {ex.Message}");
+            }
```
Comment (VanJackal) [inline ViewModels/DeckViewModel.cs:147]: this can be addressed as a separate issue but we should look into global exception handling instead of catching Generic exception in a bunch of places

File: ViewModels/DeckViewModel.cs [hunk 7]
```diff
@@ -42,73 +37,114 @@ public Deck SelectedDeck
...
+
+                if (userDecks != null)
+                {
+                    UserDecks = new ObservableCollection<IDeck>(userDecks);
+                    HasDecks = true;
+                    Console.Write($"Had deck is {HasDecks}");
+                }
+                else
+                {
+                    Console.WriteLine("In here; fail");
```
Comment (VanJackal) [inline ViewModels/DeckViewModel.cs:133]: not a meaningful log message

File: ViewModels/DeckViewModel.cs [hunk 8]
```diff
@@ -42,73 +37,114 @@ public Deck SelectedDeck
...
+                    Console.WriteLine($"Fetching cards for deck: {selectedDeck.Name}");
+                    var deckCards = await selectedDeck.GetCards();
+                    if (deckCards != null)
+                    {
+                        SelectedDecksCards = new ObservableCollection<ICard>((IEnumerable<ICard>)deckCards);
+                        Console.WriteLine($"Loaded {deckCards.Count} cards for deck: {selectedDeck.Name}");
+                    }
+                    else
+                    {
+                        SelectedDecksCards = new ObservableCollection<ICard>();
```
Comment (VanJackal) [inline ViewModels/DeckViewModel.cs:95]: is there a reason not to use  Collection.clear() ?

**Review by VanJackal — CHANGES_REQUESTED** [review]

File: Services/BackendService.cs [hunk 9]
```diff
@@ -7,19 +7,39 @@ with the backend
...
+                throw new Exception(errorMessage, ex);
+            }
+            catch (Exception ex)
+            {
+                //Catch general errors and throw them up the stack
+                Console.WriteLine($"{errorMessage}", ex.Message);
+                throw new Exception(errorMessage, ex);
+            }
+        }
+
```
[the remark this answers is not in the document]
Comment (idafum) [reply Services/BackendService.cs]: this is just specific for the backend service operations. The global error catch in App.cs is just meant to catch any other unhandled exception we might have

File: App.xaml.cs [hunk 10]
```diff
@@ -1,23 +1,47 @@
...
+			Exception ex = (Exception)e.ExceptionObject;
+			HandleException(ex);
+		}
+
+		private void TaskScheduler_UnobservedTaskException(object? sender, UnobservedTaskExceptionEventArgs e)
+		{
+			HandleException(e.Exception);
+			e.SetObserved(); //Prevents the application from crashing
+		}
+
```
[the remark this answers is not in the document]
Comment (idafum) [reply App.xaml.cs]: comments added

**Review by VanJackal — APPROVED** [review]
